name: Angular CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo 'tests'

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --prod --output-hashing=none yourcast

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./public
          retention-days: 1

  deploy:
    name: deploy
    needs: [ tests, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./public

      - name: Display structure of downloaded files
        run: ls -R

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag kuchura/your-cast-frontend:1.0.1-$(echo $GITHUB_SHA | cut -c1-7)

      - name: Docker Push
        run: docker push kuchura/your-cast-frontend:1.0.1-$(echo $GITHUB_SHA | cut -c1-7)
