name: Angular build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: $
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm instll

#      - name: Run tests
#        run: npm run test:ci
#
#      - name: Build
#        run: npm run build
