name: "Update Angular Action"

on:
  schedule:
    - cron: '30 5 * * 1,3,5'

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies
        uses: fast-facts/ng-update@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
